//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesNook {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGamesNook.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono wyniku gr o id {0}&quot;.
        /// </summary>
        internal static string BoardGameResultWithIdNotFound {
            get {
                return ResourceManager.GetString("BoardGameResultWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono stoł do gry o id {0}&quot;.
        /// </summary>
        internal static string BoardGameTableWithIdNotFound {
            get {
                return ResourceManager.GetString("BoardGameTableWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono gry o nickname {0}.
        /// </summary>
        internal static string BoardGameWithIdNotFound {
            get {
                return ResourceManager.GetString("BoardGameWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono gry o nazwie {0}&quot;.
        /// </summary>
        internal static string BoardGameWithNameNotFound {
            get {
                return ResourceManager.GetString("BoardGameWithNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono uczestnika gry o nickname {0}&quot;.
        /// </summary>
        internal static string GameParticipationWithIdNotFound {
            get {
                return ResourceManager.GetString("GameParticipationWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono gry dla gracza o nickname {0}.
        /// </summary>
        internal static string GamerBoardGameWithIdNotFound {
            get {
                return ResourceManager.GetString("GamerBoardGameWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Istnieje gracz o nickname {0}. Wybierz inny nickname.&quot;.
        /// </summary>
        internal static string GamerNicknameExists {
            get {
                return ResourceManager.GetString("GamerNicknameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie zalogowano gracza&quot;.
        /// </summary>
        internal static string GamerNotLoggedIn {
            get {
                return ResourceManager.GetString("GamerNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie zalogowano gracza o nickname {0}&quot;.
        /// </summary>
        internal static string GamerWithNicknameNotLoggedIn {
            get {
                return ResourceManager.GetString("GamerWithNicknameNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie znaleziono gry dodanej do stołu o id {0}&quot;.
        /// </summary>
        internal static string TableBoardGameWithIdNotFound {
            get {
                return ResourceManager.GetString("TableBoardGameWithIdNotFound", resourceCulture);
            }
        }
    }
}
