// Generated by typings
// Source: scripts/TypeLite.Net4.d.ts
declare module Models {
	interface Gamer {
        Nick: string;
        Name: string;
        Surname: string;
        Age: number;
        City: string;
        Street: string;
        Active: boolean;
	}
}
declare module Models.ViewModel {
	interface JSONReturnVM<T> {
		element: T;
		errormessage: string;
		haserror: boolean;
	}
}